### ISSUE TITLE
[enhancement] Replace requests by aiohttp

### ISSUE THREAD

**Issue by Sergeileduc** [Azrood/DCTbot#23]
Since aiohttp is a dependacy of discord.py, and it's not source of more import problems or anything, we should probably start replacing requests.get() calls by async aiohttp calls.

https://github.com/Azrood/DCTbot/blob/2f317e9827277a0de516075041d7d5cced2b0d4a/utils/tools.py#L3

https://github.com/Azrood/DCTbot/blob/2353dd7751fa455b036a23bbbbd8e1f37157c36d/utils/tools.py#L32

https://github.com/Azrood/DCTbot/blob/2f317e9827277a0de516075041d7d5cced2b0d4a/utils/tools.py#L49

**Comment by Sergeileduc** [comment]
Calls to requests in header.py too

https://github.com/Azrood/DCTbot/blob/2f317e9827277a0de516075041d7d5cced2b0d4a/utils/header.py#L36

**Comment by Azrood** [comment]
Got it ! Will look into that when I'm free.

Also in 
https://github.com/Azrood/DCTbot/blob/2f317e9827277a0de516075041d7d5cced2b0d4a/utils/google.py#L34

**Comment by Sergeileduc** [comment]
And getcomics :

https://github.com/Azrood/DCTbot/blob/2353dd7751fa455b036a23bbbbd8e1f37157c36d/utils/getcomics.py#L42

**Comment by Azrood** [comment]
Done with this. Only needs testing before pushing and merging.

**Comment by Azrood** [comment]
Okay I got several errors, I think this is gonna take longer than expected. :sweat_smile:

**Comment by Azrood** [comment]
okay all tests are clear except urban.
@Sergeileduc can't have async / await in magic methods( `__init__`  in UrbanSearch) So we probably should have a dedicated function with requests for UrbanSearch
