### ISSUE TITLE
[enhancement] bonjourmadame loop and weekday in bot.py

### ISSUE THREAD

**Issue by Sergeileduc** [Azrood/DCTbot#24]
Replace 10 by 24 hours (frequency)

https://github.com/Azrood/DCTbot/blob/2f317e9827277a0de516075041d7d5cced2b0d4a/bot.py#L488

Also :

with date lib
test date.today().weekday() value to see if not Saturday or Sunday

[date.weekday()](https://docs.python.org/fr/3/library/datetime.html#datetime.date.weekday)

**Comment by Azrood** [comment]
Done
