### ISSUE TITLE
if ctx.author.top_role > XXX is no longer needed

### ISSUE THREAD

**Issue by Sergeileduc** [Azrood/DCTbot#34]
We have to test it, but I think the tests : 

https://github.com/Azrood/DCTbot/blob/017cd0ac011c9fb6a114b8b1d7e3a4a2171f422a/bot.py#L386

https://github.com/Azrood/DCTbot/blob/017cd0ac011c9fb6a114b8b1d7e3a4a2171f422a/bot.py#L397

in gifadd and gifdelete are not needed anymore, since we use the decorator @commands.is_owner

https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.is_owner

**Comment by Azrood** [comment]
Ah yes, forgot to remove them.

**Comment by Azrood** [comment]
Ran some tests, we don't need them anymore. Will fix it by directly pushing to `dev2` branch if it's ok
