### ISSUE TITLE
log-enhance

### ISSUE THREAD

**Issue by Azrood** [Azrood/DCTbot#45]
I love this 
https://github.com/Azrood/DCTbot/commit/1a8e1bb6594536bf73bf32cd29695da5e1e5cb13

It's really smart and interesting, but it's not working ! 🤣🤣

**Comment by Sergeileduc** [comment]
should work now ! @Azrood

**Comment by Sergeileduc** [comment]
ok
I replaced discord utils.get by discord utils.find, and I wrote my own filter, to be case insensitive.

should work, now.

**Comment by Azrood** [comment]
okay, will run some tests and merge if they all work :+1:
