### ISSUE TITLE
Typo in roulette

### ISSUE THREAD

**Issue by Sergeileduc** [Azrood/DCTbot#59]
typo in :

J'en connais qui a vu la mort devant en face !

**Comment by Azrood** [comment]
Yeah there are other typos as well.

https://github.com/Azrood/DCTbot/blob/0b09d689035d13afed54b8ed60a461d174671410/bot.py#L228

And

https://github.com/Azrood/DCTbot/blob/0b09d689035d13afed54b8ed60a461d174671410/bot.py#L64

**Comment by Azrood** [comment]
Done
