### ISSUE TITLE
Replace channel name

### ISSUE THREAD

**Issue by Azrood** [Azrood/DCTbot#63]
Replace "roles" with "general" in

https://github.com/Azrood/DCTbot/blob/b5b1b5967351084907d7548bea9842cc52eedfb3/bot.py#L95

**Comment by Sergeileduc** [comment]
Yeah.

And while doing it, I'm wondering...

Since "get" is a very common name, and can be confusing :

Maybe calling it with its full package name (and remove the unecessary import) would be better (and more "self doumented code", in this case)

```python
channel_general = discord.utils.get(bot.guild.text_channels, name='general')
```

Decision is yours.

**Comment by Azrood** [comment]
Fixed
